from tkinter import *
root=Tk()
frame=Frame(root)
button1=Button(frame,text="button 1")
button2=Button(frame,text="button 2")
button3=Button(frame,text="button 3")
button1.pack(side=LEFT)
button2.pack(side=LEFT)
button3.pack(side=LEFT)
frame.pack()
bottomframe=Frame(root)
button4=Button(bottomframe,text="button 4")
button4.pack()
bottomframe.pack()
root.mainloop()
